`timescale 1ns/1ps
//////////////////////////////////////////////////////////////////////////////
// i2s_audio_model.v
// I2S audio transmitter stimulus (simulation only)
// Generates SCK, WS (LRCLK), and SD (serial data, MSB-first).
// Left channel from sample memory, right channel = 0 (mono).
//
// Rewritten as a synthesizable-style state machine driven by sys_clk.
// SCK is generated by a counter-based divider. The testbench provides
// sys_clk which must be fast enough to divide down to the SCK frequency.
//////////////////////////////////////////////////////////////////////////////
module i2s_audio_model #(
    parameter SAMPLE_BITS = 16,
    parameter SAMPLE_RATE = 16000,
    parameter SYS_CLK_HZ  = 100000000,  // system clock frequency
    parameter AUDIO_FILE  = "audio_samples.hex"
)(
    input  wire                    clk,       // system clock
    input  wire                    rst_n,
    input  wire                    enable,
    output reg                     sck,       // serial clock = 32 * SAMPLE_RATE
    output reg                     ws,        // word select / LRCLK (0=left, 1=right)
    output reg                     sd,        // serial data, MSB first
    output reg                     sample_valid
);

    // -----------------------------------------------------------------------
    // SCK period calculation
    // SCK frequency = 32 * SAMPLE_RATE  (16 bits * 2 channels)
    // -----------------------------------------------------------------------
    localparam integer SCK_FREQ    = 32 * SAMPLE_RATE;
    // Half-period in sys_clk cycles
    localparam integer SCK_HALF_CLKS = SYS_CLK_HZ / (2 * SCK_FREQ);

    // -----------------------------------------------------------------------
    // Sample memory
    // -----------------------------------------------------------------------
    reg [SAMPLE_BITS-1:0] sample_mem [0:65535];
    reg [15:0]            sample_idx;

    // -----------------------------------------------------------------------
    // 1 kHz sine lookup table (16 samples per cycle at 16 kHz)
    // -----------------------------------------------------------------------
    reg [SAMPLE_BITS-1:0] sine_lut [0:15];
    initial begin
        // 16-sample 1kHz sine -- values scaled to signed 16-bit range
        sine_lut[ 0] = 16'h0000;
        sine_lut[ 1] = 16'h30FB;
        sine_lut[ 2] = 16'h5A82;
        sine_lut[ 3] = 16'h7641;
        sine_lut[ 4] = 16'h7FFF;
        sine_lut[ 5] = 16'h7641;
        sine_lut[ 6] = 16'h5A82;
        sine_lut[ 7] = 16'h30FB;
        sine_lut[ 8] = 16'h0000;
        sine_lut[ 9] = 16'hCF05;
        sine_lut[10] = 16'hA57E;
        sine_lut[11] = 16'h89BF;
        sine_lut[12] = 16'h8001;
        sine_lut[13] = 16'h89BF;
        sine_lut[14] = 16'hA57E;
        sine_lut[15] = 16'hCF05;
    end

    // -----------------------------------------------------------------------
    // Audio file load -- fallback to sine LUT
    // -----------------------------------------------------------------------
    reg use_sine;
    integer init_i;

    initial begin
        use_sine = 1'b0;
        for (init_i = 0; init_i < 65536; init_i = init_i + 1)
            sample_mem[init_i] = {SAMPLE_BITS{1'b0}};

        $readmemh(AUDIO_FILE, sample_mem);

        // Heuristic: if first 4 samples are zero, assume file not loaded
        if (sample_mem[0] == {SAMPLE_BITS{1'b0}} &&
            sample_mem[1] == {SAMPLE_BITS{1'b0}} &&
            sample_mem[2] == {SAMPLE_BITS{1'b0}} &&
            sample_mem[3] == {SAMPLE_BITS{1'b0}}) begin
            $display("[%0t] i2s_audio_model: AUDIO_FILE not found or empty, using 1kHz sine", $time);
            use_sine = 1'b1;
        end
    end

    // -----------------------------------------------------------------------
    // State machine definitions
    // -----------------------------------------------------------------------
    localparam ST_IDLE       = 3'd0;
    localparam ST_LEFT_DATA  = 3'd1;
    localparam ST_LEFT_PAD   = 3'd2;
    localparam ST_RIGHT_DATA = 3'd3;
    localparam ST_ADVANCE    = 3'd4;

    reg [2:0]  fsm_state;
    reg [31:0] sck_cnt;                    // counter for SCK half-period
    reg        sck_toggle;                 // signals SCK edge
    reg [4:0]  bit_idx;                    // current bit within channel (0..15)
    reg [SAMPLE_BITS-1:0] tx_shift;        // shift register

    // -----------------------------------------------------------------------
    // State machine -- single posedge clk block
    // -----------------------------------------------------------------------
    always @(posedge clk) begin
        if (!rst_n) begin
            sck          <= 1'b0;
            ws           <= 1'b0;
            sd           <= 1'b0;
            sample_valid <= 1'b0;
            sample_idx   <= 16'd0;
            fsm_state    <= ST_IDLE;
            sck_cnt      <= 32'd0;
            sck_toggle   <= 1'b0;
            bit_idx      <= 5'd0;
            tx_shift     <= {SAMPLE_BITS{1'b0}};
        end else begin
            sck_toggle <= 1'b0;

            // SCK divider -- always runs when enabled
            if (fsm_state != ST_IDLE) begin
                if (sck_cnt >= SCK_HALF_CLKS - 1) begin
                    sck_cnt    <= 32'd0;
                    sck        <= ~sck;
                    sck_toggle <= 1'b1;
                end else begin
                    sck_cnt <= sck_cnt + 32'd1;
                end
            end

            case (fsm_state)
                ST_IDLE: begin
                    sck          <= 1'b0;
                    ws           <= 1'b0;
                    sd           <= 1'b0;
                    sample_valid <= 1'b0;
                    sample_idx   <= 16'd0;
                    sck_cnt      <= 32'd0;
                    if (enable) begin
                        // Load first sample
                        if (use_sine)
                            tx_shift <= sine_lut[0];
                        else
                            tx_shift <= sample_mem[0];
                        ws           <= 1'b0;      // left channel
                        sample_valid <= 1'b1;
                        bit_idx      <= 5'd0;
                        fsm_state    <= ST_LEFT_DATA;
                    end
                end

                ST_LEFT_DATA: begin
                    // Transmit left channel bits on SCK falling edge
                    if (sck_toggle && sck == 1'b0) begin
                        // Falling edge of SCK: shift out MSB
                        sd       <= tx_shift[SAMPLE_BITS-1];
                        tx_shift <= {tx_shift[SAMPLE_BITS-2:0], 1'b0};
                        bit_idx  <= bit_idx + 5'd1;

                        // Deassert sample_valid after first bit
                        sample_valid <= 1'b0;

                        if (bit_idx >= SAMPLE_BITS - 1) begin
                            bit_idx <= 5'd0;
                            if (SAMPLE_BITS < 16)
                                fsm_state <= ST_LEFT_PAD;
                            else begin
                                ws        <= 1'b1;  // switch to right channel
                                tx_shift  <= {SAMPLE_BITS{1'b0}};
                                fsm_state <= ST_RIGHT_DATA;
                            end
                        end
                    end
                end

                ST_LEFT_PAD: begin
                    // Pad remaining bits if SAMPLE_BITS < 16
                    if (sck_toggle && sck == 1'b0) begin
                        sd      <= 1'b0;
                        bit_idx <= bit_idx + 5'd1;
                        if (bit_idx >= 16 - SAMPLE_BITS - 1) begin
                            bit_idx   <= 5'd0;
                            ws        <= 1'b1;  // switch to right channel
                            tx_shift  <= {SAMPLE_BITS{1'b0}};
                            fsm_state <= ST_RIGHT_DATA;
                        end
                    end
                end

                ST_RIGHT_DATA: begin
                    // Transmit right channel (all zeros) -- 16 bits
                    if (sck_toggle && sck == 1'b0) begin
                        sd      <= 1'b0;
                        bit_idx <= bit_idx + 5'd1;
                        if (bit_idx >= 15) begin
                            bit_idx   <= 5'd0;
                            fsm_state <= ST_ADVANCE;
                        end
                    end
                end

                ST_ADVANCE: begin
                    // Advance sample index and start next left channel
                    sample_idx <= sample_idx + 16'd1;
                    ws         <= 1'b0;

                    if (use_sine)
                        tx_shift <= sine_lut[(sample_idx + 16'd1) & 16'h000F];
                    else
                        tx_shift <= sample_mem[sample_idx + 16'd1];

                    sample_valid <= 1'b1;

                    if (!enable)
                        fsm_state <= ST_IDLE;
                    else
                        fsm_state <= ST_LEFT_DATA;
                end

                default: begin
                    fsm_state <= ST_IDLE;
                end
            endcase
        end
    end

endmodule
